stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  tags:
    - shell
  script:
    - echo "static analysis"
    - exit 0
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "test"
    - cd ORtests/
    - test OpenRocketTest1.java
  allow_failure: false

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 0
  allow_failure: true
  
pages:
  stage: Build
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
   - docker

