image: node:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

stages:
  - Validate
  - Build
  - Test
  - Deploy

markdownlint:
  stage: Validate
  tags:
    - docker
  image: pipelinecomponents/markdownlint:latest
  script:
    - mdl --style all --warnings --rules ~MD013 .
  allow_failure: true
  
styletest:
  stage: Validate
  tags:
    - shell
  script:
    - echo "Beginning Checkstyle test"
    - mvn checkstyle:checkstyle
  allow_failure: true  

bugtest:
  stage: Validate
  tags:
    - shell
  script:
    - echo "Beginning SpotBugs test"
#    - mvn $MAVEN_CLI_OPTS spotbugs:check
    - mvn spotbugs:check
  allow_failure: true

build:
  stage: Build
  tags:
    - shell
  script:
    - echo "static analysis"
    - exit 0
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "Beginning unit tests"
    - mvn test
  allow_failure: false

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - cd "deploy website"
    - (curl --request GET --form token = $DEPLOY_API_TOKEN --form ref = master https://gitlab.ecs.vuw.ac.nz/api/v4/projects/6908/milestones?state=closed) > file
    - cat file
    - node parseMilestoneJson.js file
    - exit 0
  allow_failure: true
  
pages:
  stage: Build
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
   - docker
