variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

stages:
  - Lint
  - Bugs
  - Build
  - Test
  - Deploy

markdownlint:
  stage: Lint
  tags:
    - docker
  image: pipelinecomponents/markdownlint:latest
  script:
    - mdl --style all --warnings --rules ~MD013 .
  allow_failure: true

build:
  stage: Build
  tags:
    - shell
  script:
    - echo "static analysis"
    - exit 0
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "Beginning unit tests"
    - mvn test
  allow_failure: false

styletest:
  stage: Test
  tags:
    - shell
  script:
    - echo "Beginning Checkstyle test"
    - mvn checkstyle:checkstyle
  allow_failure: true  

bugtest:
#  stage: Test
  stage: Bugs
  tags:
    - shell
  script:
    - echo "Beginning SpotBugs test"
    - mvn $MAVEN_CLI_OPTS -Pcicdprofile spotbugs:spotbugs
  allow_failure: true

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 0
  allow_failure: true
  
pages:
  stage: Build
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
   - docker
